version: '3.4'

services:
  zhzt.exam.questionlib.api:
    image: ${DOCKER_REGISTRY-}zhztexamquestionlibapi
    build:
      context: .
      dockerfile: Zhzt.Exam.QuestionLib.Api/Dockerfile
      args:
        - ASPNETCORE_ENVIRONMENT_ARG=Debug
    ports:
      - "8081:80"
    command: "dotnet /app/zhzt.exam.questionlib.api.dll --urls=http://*:80 nacos:ip=192.168.2.162 nacos:port=8081"

  zhzt.exam.paperlib.api:
    image: ${DOCKER_REGISTRY-}zhztexampaperlibapi
    build:
      context: .
      dockerfile: Zhzt.Exam.PaperLib.Api/Dockerfile
      args:
        - ASPNETCORE_ENVIRONMENT_ARG=Debug
    ports:
      - "8082:80"
    command: "dotnet /app/zhzt.exam.paperlib.api.dll --urls=http://*:80 nacos:ip=192.168.2.162 nacos:port=8082"

  zhzt.exam.gateway:
    image: ${DOCKER_REGISTRY-}zhztexamgateway
    build:
      context: .
      dockerfile: Zhzt.Exam.Gateway/Dockerfile
      args:
        - ASPNETCORE_ENVIRONMENT_ARG=Debug
    ports:
      - "8080:80"
    command: "dotnet /app/zhzt.exam.gateway.dll --urls=http://*:80 nacos:ip=192.168.2.162 nacos:port=8080"