version: '3.4'

services:
  zhzt.exam.questionlib.api:
    image: ${DOCKER_REGISTRY-}zhztexamquestionlibapi
    build:
      context: .
      dockerfile: Zhzt.Exam.QuestionLib.Api/Dockerfile
      args:
        - ASPNETCORE_ENVIRONMENT_ARG=Debug
    ports:
      - "8081:80"
    volumes:
      - /c/questionlib/static:/app/static
    command: "dotnet /app/Zhzt.Exam.QuestionLib.Api.dll urls=http://*:80 nacos:ip=102.168.10.107 nacos:port=8081"

  zhzt.exam.paperlib.api:
    image: ${DOCKER_REGISTRY-}zhztexampaperlibapi
    build:
      context: .
      dockerfile: Zhzt.Exam.PaperLib.Api/Dockerfile
      args:
        - ASPNETCORE_ENVIRONMENT_ARG=Debug
    volumes:
      - /c/questionlib/papers:/app/papers
    ports:
      - "8082:80"
    command: "dotnet /app/Zhzt.Exam.PaperLib.Api.dll urls=http://*:80 nacos:ip=102.168.10.107 nacos:port=8082"
    
  zhzt.exam.auth.api:
    image: ${DOCKER_REGISTRY-}zhztexamauthapi
    build:
      context: .
      dockerfile: Zhzt.Exam.Auth.Api/Dockerfile
      args:
        - ASPNETCORE_ENVIRONMENT_ARG=Debug
    ports:
      - "8083:80"
    command: "dotnet /app/Zhzt.Exam.Auth.Api.dll urls=http://*:80 nacos:ip=102.168.10.107 nacos:port=8083"
    
  zhzt.exam.microclasslib.api:
    image: ${DOCKER_REGISTRY-}zhztexammicroclasslibapi
    build:
      context: .
      dockerfile: Zhzt.Exam.MicroClassLib.Api/Dockerfile
      args:
        - ASPNETCORE_ENVIRONMENT_ARG=Debug
    ports:
      - "8084:80"
    volumes:
      - /c/microclassvideo/static:/app/static
    command: "dotnet /app/Zhzt.Exam.MicroClassLib.Api.dll urls=http://*:80 nacos:ip=102.168.10.107 nacos:port=8084"

  zhzt.exam.documentlib.api:
    image: ${DOCKER_REGISTRY-}zhztexamdocumentlibapi
    build:
      context: .
      dockerfile: Zhzt.Exam.DocumentLib.Api/Dockerfile
      args:
        - ASPNETCORE_ENVIRONMENT_ARG=Debug
    ports:
      - "8085:80"
    volumes:
      - /c/documentlib/static:/app/static
    command: "dotnet /app/Zhzt.Exam.DocumentLib.Api.dll urls=http://*:80 nacos:ip=102.168.10.107 nacos:port=8084"


  zhzt.exam.gateway:
    image: ${DOCKER_REGISTRY-}zhztexamgateway
    build:
      context: .
      dockerfile: Zhzt.Exam.Gateway/Dockerfile
      args:
        - ASPNETCORE_ENVIRONMENT_ARG=Debug
    ports:
      - "8080:80"
    command: "dotnet /app/Zhzt.Exam.Gateway.dll urls=http://*:80 nacos:ip=102.168.10.107 nacos:port=8080"